#!/usr/bin/env node
/**
 * Parse locally downloaded zh.wikipedia "历史上的今天" pages and generate
 * src/lib/on-this-day.data.ts and src/lib/observances.data.ts
 *
 * Usage:
 * 1. Download month pages and save as: scripts/html/1月.html ... scripts/html/12月.html
 * 2. Run: node scripts/generate-on-this-day.ts
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import * as cheerio from "cheerio";

type Event = { year: number; description: string };

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ON_THIS_DAY_OUT = path.resolve(__dirname, "../src/lib/on-this-day.data.ts");
const OBSERVANCES_OUT = path.resolve(__dirname, "../src/lib/observances.data.ts");
const DIR = path.resolve(__dirname, "html");

function readFileSafe(p: string) {
  try {
    return fs.readFileSync(p, "utf8");
  } catch {
    return null;
  }
}

function parseEventsForMonth(html: string, month: number): Record<string, Event[]> {
  const $ = cheerio.load(html);
  const data: Record<string, Event[]> = {};

  // Parse by looking for .selected-anniversary blocks
  $(".selected-anniversary").each((_, s) => {
    const sel = $(s);
    // day usually appears in .otd-year (e.g. "1月1日")
    const dayText = sel.find(".otd-year").text().trim() || sel.find("> p").text().trim();
    const dayMatch = dayText.match(/(\d{1,2})日/);
    if (!dayMatch) return;
    const day = Number(dayMatch[1]);
    const key = `${month}-${day}`;
    data[key] = data[key] ?? [];

    // <dl> containing .event blocks
    sel.find(".event").each((_, ev) => {
      const evEl = $(ev);
      const dtEl = evEl.find("dt").first();
      const ddEl = evEl.find("dd").first();
      if (dtEl && dtEl.length && ddEl && ddEl.length) {
        const yearText = dtEl.text().trim();
        let year: number | null = null;
        const mPre = yearText.match(/前\s*(\d{1,4})/);
        if (mPre) year = -Number(mPre[1]);
        else {
          const m = yearText.match(/(\d{1,4})/);
          if (m) year = Number(m[1]);
        }
        const desc = ddEl.text().replace(/\s+/g, " ").trim();
        if (year !== null && desc) {
          data[key].push({ year, description: desc });
        }
      }
    });
  });

  return data;
}

function extractObservances(text: string): string[] {
  const idx = text.indexOf("：");
  const after = idx >= 0 ? text.slice(idx + 1) : text;
  return after
    .split(/[、,，;；]/)
    .map((s) => s.trim())
    .filter((part) => Boolean(part) && !/^\d+月\d+日/.test(part));
}

function parseObservancesForMonth(html: string, month: number): Record<string, string[]> {
  const $ = cheerio.load(html);
  const data: Record<string, string[]> = {};

  // Parse observances directly from .selected-anniversary blocks
  $(".selected-anniversary").each((_, s) => {
    const sel = $(s);
    const dayText = sel.find(".otd-year").text().trim() || sel.find("> p").text().trim();
    const dayMatch = dayText.match(/(\d{1,2})日/);
    if (!dayMatch) return;
    const key = `${month}-${Number(dayMatch[1])}`;
    data[key] = data[key] ?? [];

    const paragraph = sel.find("> p").first();
    if (paragraph && paragraph.length) {
      const observances = extractObservances(paragraph.text().trim());
      if (observances.length > 0) data[key].push(...observances);
    }
  });

  return data;
}

function main() {
  const eventsByDate: Record<string, Event[]> = {};
  const observancesByDate: Record<string, string[]> = {};
  for (let m = 1; m <= 12; m++) {
    // Expect filenames like "1月.html" ... "12月.html"
    const file = path.join(DIR, `${m}月.html`);
    const html = readFileSafe(file);
    if (!html) {
      console.warn(`Skipping month ${m}, file not found: ${file}`);
      continue;
    }
    const monthEvents = parseEventsForMonth(html, m);
    const monthObservances = parseObservancesForMonth(html, m);

    for (const date of Object.keys(monthEvents)) {
      eventsByDate[date] = (eventsByDate[date] ?? []).concat(monthEvents[date]);
    }
    for (const date of Object.keys(monthObservances)) {
      observancesByDate[date] = Array.from(
        new Set((observancesByDate[date] ?? []).concat(monthObservances[date]))
      );
    }
  }
  const onThisDayText = `// Auto-generated by scripts/generate-on-this-day.ts\nexport const ON_THIS_DAY = ${JSON.stringify(eventsByDate, null, 2)} as const;\n`;
  const observancesText = `// Auto-generated by scripts/generate-on-this-day.ts\nexport const OBSERVANCES = ${JSON.stringify(observancesByDate, null, 2)} as const;\n`;
  fs.writeFileSync(ON_THIS_DAY_OUT, onThisDayText, "utf8");
  fs.writeFileSync(OBSERVANCES_OUT, observancesText, "utf8");
  console.log(`Wrote ${ON_THIS_DAY_OUT}`);
  console.log(`Wrote ${OBSERVANCES_OUT}`);
}

main();
